---
matrix:
    include:
        - os: osx
          osx_image: xcode10.1
install:
  - echo | ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  - PATH="/home/homebrew/.homebrew/bin:$PATH"
  - brew install gcc
  - brew tap getantibody/tap
  - brew install getantibody/tap/antibody
  - brew install zsh-autosuggestions
  - git clone https://github.com/amerenda/dotfiles.git --recursive
  - rm -f ~/.zshrc
  - rm -f ~/.gitconfig

script:
  - cd dotfiles
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - git checkout $TRAVIS_PULL_REQUEST_BRANCH
  - /bin/sh -c './install'
  - echo | vim +PluginInstall +qall
