---
matrix:
    include:
        - os: osx
          osx_image: xcode10.1
install:
  - git clone --recurse-submodules https://github.com/amerenda/dotfiles.git
  - rm -f ~/.zshrc
  - rm -f ~/.gitconfig
  - cd dotfiles
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - git checkout $TRAVIS_PULL_REQUEST_BRANCH

script:
  - /bin/sh -c './install'
  - echo | vim +PluginInstall +qall
