---
matrix:
    include:
        - os: linux
          osx_image: xcode10.1
install:
  - echo | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - git clone git@github.com:amerenda/dotfiles.git --recursive
  - brew install getantibody/tap/antibody
  - brew install zsh-autosuggestions
  - brew install coreutils

script:
  - cd dotfiles
  - /bin/sh -c install
