---
dist: trusty

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get --yes install git

install:
  - git clone git@github.com:amerenda/dotfiles.git --recursive


script:
  - cd dotfiles
  - /bin/sh -c install

