---
matrix:
    include:
        - os: linux
          osx_image: xcode10.1
install:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  - brew install gcc
  - brew tap getantibody/tap
  - brew install getantibody/tap/antibody
  - brew install zsh-autosuggestions
  - brew install coreutils
  - git clone https://github.com/amerenda/dotfiles.git --recursive

script:
  - cd dotfiles
  - /bin/sh -c './install'
  - vim +PluginInstall +qall
