---
os:
  - osx

install:
  - rm -f ~/.zshrc
  - rm -f ~/.gitconfig
  - cd amerenda/dotfiles
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - git checkout $TRAVIS_PULL_REQUEST_BRANCH

script:
  - /bin/sh -c './install'
  - echo | vim +PluginInstall +qall
  - vim -s test/vimscript
  - ls test/vim.out 2>/dev/null || echo FAIL
