---
os:
  - osx

install:
  - rm -f ~/.zshrc
  - rm -f ~/.gitconfig
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - git checkout $TRAVIS_PULL_REQUEST_BRANCH

script:
  - brew install zsh
  - /bin/sh -c './install'
  - source ~/.zshrc
  - subup
  - echo | vim +PluginInstall +qall
  - vim -s test/vimscript
  - ls test/vim.out 2>/dev/null || echo FAIL
