---
os:
  - osx

install:
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - rm -f ~/.zshrc
  - rm -f ~/.gitconfig

script:
  - brew install zsh || echo FAIL
  - /bin/sh -c './install' || echo FAIL
  - source ~/.zshrc || echo FAIL
  - subup || echo FAIL
  - echo | vim +PluginInstall +qall || echo FAIL
  - vim -s test/vimscript
  - ls test/vim.out 2>/dev/null || echo FAIL
